# Generated by Django 3.2.16 on 2023-08-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20230816_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userCreated',
            new_name='user_creater',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userOwner',
            new_name='user_owner',
        ),
    ]
